# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix
{
  pkgs,
  fetchurl,
  fetchgit,
  fetchhg,
}: self: super: {
  "maturin" = super.buildPythonPackage rec {
    pname = "maturin";
    version = "1.13.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c7/7d/a1be934690cdcc3c6609769ceaad322ab7501c2ee5bafcac1b14d609e403/maturin-1.13.3-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.musllinux_1_1_x86_64.whl";
      sha256 = "sha256-RmfvYJq0RsG14L/k+fuZaZq22FSEM/jRpoQlbgtnIX8=";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    propagatedBuildInputs = [
      self."tomli"
    ];
  };
  "tomli" = super.buildPythonPackage rec {
    pname = "tomli";
    version = "2.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7b/61/cceae43728b7de99d9b847560c262873a1f6c98202171fd5ed62640b494b/tomli-2.4.1-py3-none-any.whl";
      sha256 = "1zj9ic1361g962pxrrsasn3nb30zimpnb1nb8gd2488k0ac8318d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "qubovert" = super.buildPythonPackage rec {
    pname = "qubovert";
    version = "1.2.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4e/99/c65c7e2a1ea5ee8e8df9669df62bf0b7fe48437d2591e5012308655cb774/qubovert-1.2.5.tar.gz";
      sha256 = "0n1fmxbn6bgxpw6qwygkbvxfc10q974z11f90k5p1psrpvk8pqgs";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
    ];
  };
  # REDACTED
}
